# Generated by Django 4.2.6 on 2023-10-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team20", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="sku_id",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
