# Generated by Django 4.2.6 on 2023-10-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team20", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="customer",
            new_name="customer_id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_id",
            field=models.IntegerField(unique=True),
        ),
    ]
