# Generated by Django 4.2.6 on 2023-10-27 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team20", "0002_alter_customer_customer_id_alter_orders_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="shape_option",
        ),
    ]
